import { defineConfig } from 'tsdown';

export default defineConfig([
  {
    entry: ['src/index.node.ts'],
    format: ['esm'],
    platform: 'node',
    outDir: 'dist/node',
    minify: false,
    dts: true,
    sourcemap: true,
    clean: true,
    deps: { neverBundle: [/^node:/] },
  },
  {
    entry: ['src/index.browser.ts'],
    format: ['esm'],
    platform: 'browser',
    outDir: 'dist/browser',
    minify: true,
    dts: true,
    sourcemap: true,
    clean: true,
    deps: { neverBundle: [/^node:/] },
  },
  {
    entry: ['src/index.cli.ts'],
    format: ['esm'],
    platform: 'node',
    outDir: 'dist/cli',
    minify: false,
    dts: true,
    sourcemap: true,
    clean: true,
    deps: { neverBundle: ['@elek-io/core', /^node:/] },
  },
  {
    entry: ['src/index.astro.ts'],
    format: ['esm'],
    platform: 'node',
    outDir: 'dist/astro',
    minify: false,
    dts: true,
    sourcemap: true,
    clean: true,
    deps: { neverBundle: ['astro/loaders', /^node:/] },
  },
]);
