import { CoreError } from '../util/shared.js';

/**
 * The minimum an Astro content entry has to look like to be routed by
 * one of its slug fields
 */
export interface ElekRoutableEntry {
  id: string;
  data: Record<string, unknown>;
}

/**
 * The languages an Entry holds a given field in.
 *
 * A Value generated by the loaders is keyed by the Project's languages,
 * so the field itself names them and a page never has to. An Entry that
 * was built by hand carries no such information, and falls back to
 * `string` rather than to `never`.
 */
export type ElekEntryLanguage<E extends ElekRoutableEntry, F extends string> =
  E['data'][F] extends Record<infer Language extends string, unknown>
    ? Language
    : string;

export interface ElekSlugPathsProps<
  E extends ElekRoutableEntry,
  F extends string,
> {
  /** Field definition slug of the slug field to route by */
  slugField: F;
  /**
   * Route a single language, so the params hold the slug alone. Omit
   * to route every language, which adds the language to the params.
   */
  language?: ElekEntryLanguage<E, F>;
}

export interface ElekSlugPath<
  E extends ElekRoutableEntry,
  F extends string = string,
> {
  params: { slug: string; language?: string };
  props: { entry: E; language: ElekEntryLanguage<E, F> };
}

/**
 * A slug Value is translatable, so it holds one slug per language and
 * `null` where an Entry has none
 */
function isTranslatable<Language extends string>(
  value: unknown
): value is Record<Language, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * The languages a translatable Value holds.
 *
 * `Object.keys` is typed as returning `string[]` whatever it is handed,
 * because a JavaScript object may carry keys its type does not mention.
 * A Value read from a Project cannot: the loaders build it from the
 * Project's languages. Asserting that once here keeps the rest of the
 * routing typed without repeating it per call.
 */
function languagesOf<Language extends string>(
  value: Record<Language, unknown>
): Language[] {
  return Object.keys(value) as Language[];
}

/**
 * Turns Entries into the paths a `getStaticPaths` returns, routing
 * them by one of their slug fields instead of by their UUID.
 *
 * Every language of the Collection gets its own path, with the
 * language in the params, unless a single one is asked for. An Entry
 * without a slug in a language is left out of that language, it has no
 * public URL there.
 *
 * A Collection can define any number of slug fields, so the field to
 * route by is named per call. Entries stay keyed by their UUID in
 * Astro's store, which is what `getEntry()` and every reference
 * lookup keeps using.
 *
 * Each path carries the language it was built for, typed as the
 * Project's languages, so a page reads a translatable Value without
 * naming them. `Astro.params` cannot do this, it types every route
 * param as `string | undefined`.
 *
 * @example
 * ```ts
 * // src/pages/[language]/[slug].astro
 * export async function getStaticPaths() {
 *   const posts = await getCollection('websitePosts');
 *   return elekSlugPaths(posts, { slugField: 'slug' });
 * }
 *
 * const { entry, language } = Astro.props;
 * // <h1>{entry.data.title[language]}</h1>
 * ```
 */
export function elekSlugPaths<
  E extends ElekRoutableEntry,
  F extends keyof E['data'] & string,
>(entries: E[], props: ElekSlugPathsProps<E, F>): ElekSlugPath<E, F>[] {
  const paths: ElekSlugPath<E, F>[] = [];

  for (const entry of entries) {
    const value = entry.data[props.slugField];
    if (!isTranslatable<ElekEntryLanguage<E, F>>(value)) {
      throw CoreError.badRequest(
        `Entry "${entry.id}" has no slug field "${props.slugField}" to route by. Name a slug field of the Collection, its Entries hold one slug per language.`
      );
    }

    if (props.language !== undefined && !(props.language in value)) {
      throw CoreError.badRequest(
        `Entry "${entry.id}" has no language "${props.language}". The Project supports: ${Object.keys(value).join(', ')}.`
      );
    }

    // The keys of a translatable Value are the Project's languages,
    // which is what types the language handed to the page
    const languages: ElekEntryLanguage<E, F>[] =
      props.language === undefined ? languagesOf(value) : [props.language];

    for (const language of languages) {
      const slug = value[language];
      // Null is the normal state for an Entry that is not published in
      // a language, it simply gets no path there
      if (typeof slug !== 'string' || slug === '') {
        continue;
      }
      paths.push({
        params: props.language === undefined ? { language, slug } : { slug },
        props: { entry, language },
      });
    }
  }

  return paths;
}
