import { CoreError } from '../util/shared.js';
import { keysOf } from '../util/typedObject.js';

/**
 * The minimum an Astro content entry has to look like to be routed by
 * one of its slug fields
 */
export interface ElekRoutableEntry {
  id: string;
  data: Record<string, unknown>;
}

/**
 * The languages an Entry holds a given field in.
 *
 * A Value generated by the loaders is keyed by the Project's languages,
 * so the field itself names them and a page never has to. An Entry that
 * was built by hand carries no such information, and falls back to
 * `string` rather than to `never`.
 */
export type ElekEntryLanguage<E extends ElekRoutableEntry, F extends string> =
  E['data'][F] extends Record<infer Language extends string, unknown>
    ? Language
    : string;

export interface ElekSlugPathsProps<
  E extends ElekRoutableEntry,
  F extends string,
> {
  /** Field definition slug of the slug field to route by */
  slugField: F;
  /**
   * Route a single language, so the params hold the slug alone. Omit
   * to route every language, which adds the language to the params.
   */
  language?: ElekEntryLanguage<E, F>;
}

export interface ElekSlugPath<
  E extends ElekRoutableEntry,
  F extends string = string,
> {
  params: { slug: string; language?: string };
  props: { entry: E; language: ElekEntryLanguage<E, F> };
}

/**
 * A slug Value is translatable, so it holds one slug per language and
 * `null` where an Entry has none
 */
function isTranslatable<Language extends string>(
  value: unknown
): value is Record<Language, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * The languages a translatable Value holds.
 *
 * A Value read from a Project is keyed by the Project's languages, because
 * the loaders build it that way, so its own key type is the answer. See
 * `keysOf` for why reading those keys needs a helper at all.
 */
function languagesOf<Language extends string>(
  value: Record<Language, unknown>
): Language[] {
  return keysOf(value);
}

/**
 * Turns Entries into the paths a `getStaticPaths` returns, routing them by one
 * of their slug fields instead of by their UUID.
 *
 * Every language of the Collection gets its own path, with the language in the
 * params, unless a single one is asked for. An Entry without a slug in a
 * language is left out of that language. Each path carries its language typed
 * as the Project's languages, which `Astro.params` cannot do, and Entries stay
 * keyed by their UUID in Astro's store, which `getEntry()` keeps using.
 *
 * @see ../../docs/usage.md
 */
export function elekSlugPaths<
  E extends ElekRoutableEntry,
  F extends keyof E['data'] & string,
>(entries: E[], props: ElekSlugPathsProps<E, F>): ElekSlugPath<E, F>[] {
  const paths: ElekSlugPath<E, F>[] = [];

  for (const entry of entries) {
    const value = entry.data[props.slugField];
    if (!isTranslatable<ElekEntryLanguage<E, F>>(value)) {
      throw CoreError.badRequest(
        `Entry "${entry.id}" has no slug field "${props.slugField}" to route by. Name a slug field of the Collection, its Entries hold one slug per language.`
      );
    }

    if (props.language !== undefined && !(props.language in value)) {
      throw CoreError.badRequest(
        `Entry "${entry.id}" has no language "${props.language}". The Project supports: ${Object.keys(value).join(', ')}.`
      );
    }

    // The keys of a translatable Value are the Project's languages,
    // which is what types the language handed to the page
    const languages: ElekEntryLanguage<E, F>[] =
      props.language === undefined ? languagesOf(value) : [props.language];

    for (const language of languages) {
      const slug = value[language];
      // Null is the normal state for an Entry that is not published in
      // a language, it simply gets no path there
      if (typeof slug !== 'string' || slug === '') {
        continue;
      }
      paths.push({
        params: props.language === undefined ? { language, slug } : { slug },
        props: { entry, language },
      });
    }
  }

  return paths;
}
