import Fs from 'fs-extra';
import Path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import core, { type Project, uuid } from '../test/setup.js';
import { createCollection, createProject, expectTranspiles } from '../test/util.js';
import { generateApiClientAction } from './generateApiClientAction.js';

/**
 * Exercises the TypeScript generation path: generateApiClientAction ->
 * generateApiClient and the writer helpers it drives. The `language: 'js'`
 * tsdown compilation is exercised separately as a smoke test below; the
 * watch/process.exit wrapper is intentionally not covered.
 */
describe('generateApiClientAction (TypeScript output)', () => {
  let project: Project & { destroy: () => Promise<void> };
  let collectionSlugPlural: string;
  let outDir: string;
  let client: string;

  beforeAll(async () => {
    project = await createProject('generateApiClient Test');
    const collection = await createCollection(project.id);
    collectionSlugPlural = collection.slug.plural;
    outDir = Path.join(core.util.pathTo.tmp, `api-client-${uuid()}`);

    await generateApiClientAction({
      outDir,
      language: 'ts',
      format: 'esm',
      target: 'es2020',
      options: { watch: false },
    });

    client = await Fs.readFile(
      Path.join(Path.resolve(outDir), 'client.ts'),
      'utf-8'
    );
  }, 30000);

  afterAll(async () => {
    await project.destroy();
    await Fs.remove(outDir);
  });

  it('writes the auto-generated header and Core import', () => {
    expect(client).toContain('Auto-generated by elek.io Core');
    expect(client).toContain(`from '@elek-io/core'`);
  });

  it('exposes the content.v1 apiClient surface', () => {
    expect(client).toContain('export function apiClient');
    expect(client).toContain('content:');
    expect(client).toContain('v1:');
    expect(client).toContain('projects:');
  });

  it('includes the generated Project and Collection', () => {
    expect(client).toContain(project.id);
    expect(client).toContain(collectionSlugPlural);
  });

  it('emits the entries.list fetch with schema parsing and typed cast', () => {
    expect(client).toContain('getEntrySchemaFromFieldDefinitions');
    expect(client).toContain('await fetch');
    expect(client).toContain('as unknown as PaginatedList');
  });

  it('also emits a generated types file alongside the client', async () => {
    const files = await Fs.readdir(Path.resolve(outDir));
    expect(files.some((f) => f.startsWith('types') && f.endsWith('.ts'))).toBe(
      true
    );
  });

  it('emits client and types that transpile without syntax errors', async () => {
    // Substring assertions check intent; transpile every emitted .ts file so a
    // malformed client OR a malformed types blob is caught. The types file is
    // where broken type literals are most likely to land.
    const dir = Path.resolve(outDir);
    const files = (await Fs.readdir(dir)).filter((f) => f.endsWith('.ts'));
    expect(files.length).toBeGreaterThan(0);
    for (const file of files) {
      const source = await Fs.readFile(Path.join(dir, file), 'utf-8');
      expectTranspiles(source, file);
    }
  });
});

/**
 * Pipeline smoke test for the product's own `language: 'js'` command. This is
 * NOT a type-check against Core: generateApiClientAction marks '@elek-io/core'
 * and 'zod' as external, so tsdown's .d.ts emit never resolves or checks the
 * types the client imports from Core. What it verifies is that the real
 * command runs end-to-end - the generated output parses, bundles, the
 * glob/entry handling and source cleanup work, and .js + .d.ts land on disk.
 */
describe('generateApiClientAction (JavaScript pipeline smoke test)', () => {
  let project: Project & { destroy: () => Promise<void> };
  let outDir: string;

  beforeAll(async () => {
    project = await createProject('generateApiClient JS Smoke Test');
    await createCollection(project.id);
    outDir = Path.join(core.util.pathTo.tmp, `api-client-js-${uuid()}`);
  }, 30000);

  afterAll(async () => {
    await project.destroy();
    await Fs.remove(outDir);
  });

  it(
    'bundles to .js and emits .d.ts (pipeline only, not type-checked against Core)',
    { timeout: 60000 },
    async () => {
      await generateApiClientAction({
        outDir,
        language: 'js',
        format: 'esm',
        target: 'es2020',
        options: { watch: false },
      });

      const files = await Fs.readdir(Path.resolve(outDir));
      // The TS *sources* are removed after compilation in the 'js' path.
      // Declaration files (.d.ts/.d.mts) are emitted output, not sources.
      const remainingTsSources = files.filter(
        (f) => f.endsWith('.ts') && !f.endsWith('.d.ts')
      );
      expect(remainingTsSources).toEqual([]);
      expect(files.some((f) => f.endsWith('.js') || f.endsWith('.mjs'))).toBe(
        true
      );
      expect(
        files.some((f) => f.endsWith('.d.ts') || f.endsWith('.d.mts'))
      ).toBe(true);
    }
  );
});
