import chokidar from 'chokidar';
// Type-only, so it is erased at build time and tsdown stays out of the bundle
import type { build } from 'tsdown';
import ElekIoCore from '../index.node.js';
import type { ConstructorElekIoCoreProps } from '../schema/index.js';
import { CoreError } from '../util/shared.js';

/**
 * The log level is left out on purpose, so ELEK_IO_LOG_LEVEL reaches
 * the CLI's Core. An option here would win over the variable.
 */
let coreProps: NonNullable<ConstructorElekIoCoreProps> = {};
let coreInstance: ElekIoCore | undefined;

/**
 * Overrides the props the CLI creates its Core instance with,
 * e.g. from the global --data-dir option
 *
 * Must be called before the first getCore call.
 */
export function configureCore(
  props: NonNullable<ConstructorElekIoCoreProps>
): void {
  if (coreInstance) {
    throw new Error(
      'configureCore must be called before the first getCore call'
    );
  }
  coreProps = { ...coreProps, ...props };
}

/**
 * Returns the Core instance shared by all CLI actions, creating it on first use
 *
 * Lazy so that importing the CLI has no filesystem side effects.
 */
export function getCore(): ElekIoCore {
  coreInstance ??= new ElekIoCore(coreProps);
  return coreInstance;
}

/**
 * An open watcher on the data directory's `projects` path, which the caller
 * owns and nothing closes, so a command that calls this never exits on its
 * own. It builds the CLI's Core through `getCore()` when none exists yet,
 * which fixes the directory being watched.
 *
 * The initial scan is skipped so a first run does not fire one event per
 * existing file, and `.git` is ignored so Core's own git writes do not
 * retrigger the regeneration that caused them.
 */
export function watchProjects() {
  return chokidar.watch(getCore().util.pathTo.projects, {
    ignoreInitial: true, // Do not regenerate Client while chokidar first discovers all directories and files
    ignored: isInsideGitDirectory, // Exclude all files inside .git directory of Project repositories
  });
}

/**
 * Whether the path points inside a Project's `.git` directory, whose churn
 * says nothing about the content the generators read.
 *
 * Matches either separator, because chokidar hands back native paths and a
 * POSIX-only test would watch every git internal on Windows.
 */
export function isInsideGitDirectory(path: string): boolean {
  return /[/\\]\.git[/\\]/.test(path);
}

/**
 * Loads tsdown, which compiles the generated TypeScript to JavaScript.
 *
 * The import is lazy and tsdown is an optional peer dependency, so the CLI
 * bundle does not contain it. Bundling it pulls in rolldown, whose native
 * binding cannot be bundled, and every command dies at startup.
 *
 * Only the `js` language needs it, so an install without it keeps working
 * for every other command.
 */
export async function loadCompiler(): Promise<typeof build> {
  try {
    const { build } = await import('tsdown');
    return build;
  } catch (error) {
    throw CoreError.preconditionFailed(
      'Generating JavaScript needs the optional peer dependencies "tsdown" and "typescript". Install both as dev dependencies of your project, or pass "ts" as the language to generate TypeScript instead.',
      error
    );
  }
}

/**
 * Header written at the top of every auto-generated file.
 */
export const AUTO_GENERATED_HEADER = [
  '// Auto-generated by elek.io Core - do not edit manually.',
  '// Re-run the appropriate `elek generate:*` command to update.',
].join('\n');

/**
 * Converts a kebab-case slug to PascalCase.
 * e.g. "blog-post" -> "BlogPost", "hero-section" -> "HeroSection"
 */
export function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Escapes a string for use inside a single-quoted TypeScript literal.
 *
 * A line break goes with the quote and the backslash. The literal is one
 * line of source, so a raw one ends the line rather than the string and
 * the generated file no longer parses. Three free-form inputs reach here:
 * a textarea `defaultValue`, a string select's `option.value` and
 * `ofAssetMimeTypes`.
 */
export function escapeForSingleQuotedString(s: string): string {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n');
}
