import chokidar from 'chokidar';
import ElekIoCore from '../index.node.js';

export const core = new ElekIoCore({
  log: {
    level: 'info',
  },
});

export function watchProjects() {
  return chokidar.watch(core.util.pathTo.projects, {
    ignoreInitial: true, // Do not regenerate Client while chokidar first discovers all directories and files
    ignored: (path) => path.includes('/.git/'), // Exclude all files inside .git directory of Project repositories
  });
}

/**
 * Header written at the top of every auto-generated file.
 */
export const AUTO_GENERATED_HEADER = [
  '// Auto-generated by elek.io Core - do not edit manually.',
  '// Re-run the appropriate `elek generate:*` command to update.',
].join('\n');

/**
 * Converts a kebab-case slug to PascalCase.
 * e.g. "blog-post" -> "BlogPost", "hero-section" -> "HeroSection"
 */
export function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Escapes a string for use inside a single-quoted TypeScript literal.
 */
export function escapeForSingleQuotedString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
