name: CD
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js 22 environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint, check types and formatting
        run: pnpm run lint && pnpm run check-types && pnpm run check-format
      - name: Run tests with coverage
        run: pnpm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: pnpm run build
      - name: Create pull request or publish to NPM
        uses: changesets/action@v1
        with:
          title: 'WIP: Release x.x.x'
          commit: Release new version
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
