name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Testing on ${{ matrix.platform }} with Node.js ${{ matrix.node-version }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # macos-12 = intel
        # macos-14 = M1 (arm)
        platform: [ubuntu-22.04, macos-12, macos-14, windows-2022]
        node-version: [20]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ic
      - name: Run linter
        run: npm run lint
      - name: Run tests with coverage
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: npm run build
