name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    name: Linting, testing and publishing code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: yarn install
        
      - name: Lint, test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: cf10f2b1011c521bc8b18392a62a9db4920821861e265aa96962107ae6425b86
        with:
          coverageCommand: yarn test:full:ci
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true