name: CI
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Testing on ${{ matrix.platform }} with Node.js ${{ matrix.node-version }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        # macos-13 = intel
        # macos-14+ = M1 (arm)
        platform: [ubuntu-24.04, macos-13, macos-15, windows-2025]
        node-version: [22]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js ${{ matrix.node-version }} environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint, check types and formatting
        run: pnpm run lint && pnpm run check-types && pnpm run check-format
      - name: Run tests with coverage
        run: pnpm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: pnpm run build
